# Site settings

title: Santa Monica CityNet
baseurl: "/"
url: "http://www.smcitynet.com" # the base hostname & protocol for your site

contact:
    phone: "3104342612" # treat this like a string
    email: gary.carter@smgov.net

social:
    - icon: twitter
      site: https://twitter.com/SMCityNet
    - icon: youtube
      site: https://www.youtube.com/channel/UCRgGqJaU9t12Qr4lE2moevQ


# Build Settings

markdown: redcarpet
sass:
    style: compressed