- name: Broadband
  slug: broadband
  jsid: Services-Broadband
  images:
    - 100mb
    - 1gb
    - 10gb
    - 100gb
    
- name: Wavelengths
  slug: wavelengths
  jsid: Services-Wavelengths
  services:
    - 1 GB
    - 10 GB
    - 100 GB
    
- name: Dark Fiber
  slug: darkfiber
  jsid: Services-DarkFiber
  services:
    - Point-to-Point Topology
    - Ring Topology
    - Mesh Topology
