- name: Broadband
  slug: broadband
  jsid: Services-Broadband
  header: Compare Broadband Speeds
  description: >-
    For Post Production: Download a 40GB Blu-Ray Movie
  epilogue: Estimated Transfer Time
  button: true
  idTarget: "monitors-start"
  meta:
    images:
      - name: 100mb
        time: 57m
        image: climbing.png
      - name: 1gb
        time: 6m
        image: avalanche.png
      - name: 10gb
        time: 33s
        image: celebrating.png
      - name: 100gb
        time: 3s
        image: ending.png
        #include: partials/broadband-video.html

- name: Wavelengths
  slug: wavelengths
  jsid: Services-Wavelengths
  header: Compare Wavelengths Speeds
  description: >-
    For Disaster Recovery: Transfer 2TB Production File to DR Site
  epilogue: Estimated Transfer Time
  button: true
  idTarget: "wavelengths-start"
  meta:
    gauges:
      - name: large
        size: 300
        color: "#54A9A4"
        thickness: 0.3
        value: 75
      - name: medium
        size: 200
        color: "#389898"
        thickness: 0.45
        value: 50
      - name: small
        size: 100
        color: "#2E8995"
        thickness: 0.7
        value: 15

- name: Dark Fiber
  slug: darkfiber
  jsid: Services-DarkFiber
  header: Compare Network Topology Options
  description: >-
    For Network Architecture: Provision Private Dark Fiber Network