- name: Broadband
  slug: broadband
  jsid: Services-Broadband
  header: Compare Broadband Speeds
  description: For downloading a 40GB Blu-ray Movie
  epilogue: Estimated Transfer Time
  meta:
    images:
      - name: 100mb
        time: 57m
        image: universal-logo.png
      - name: 1gb
        time: 6m
        image: avalanche.png
      - name: 10gb
        time: 33s
        image: everest.png
      - name: 100gb
        time: 3s
        include: partials/broadband-video.html

- name: Wavelengths
  slug: wavelengths
  jsid: Services-Wavelengths
  header: Compare Wavelengths Speeds
  description: For transferring 2TB Production File to Disaster Recovery Site
  epilogue: Estimated Transfer Time

- name: Dark Fiber
  slug: darkfiber
  jsid: Services-DarkFiber
  header: Network Topology Options
  description: Provisioning private dark fiber network
